# Assignment

### GRADED : Boston housing prices
We will use the Boston house pricing dataset to predict house prices based on properties of the house

In [59]:
import numpy as np
import pandas as pd
import sklearn
from sklearn import ensemble
from sklearn import datasets
from sklearn import model_selection
import statsmodels.api as smf

boston = sklearn.datasets.load_boston()
print(boston.DESCR)

Boston House Prices dataset
===========================

Notes
------
Data Set Characteristics:

    :Number of Instances: 506

    :Number of Attributes: 13 numeric/categorical predictive

    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
        - B        1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
        - LSTAT    % lower status of the population
        - MEDV     Median value of owner-occupied homes in $1000's

    :Missing Attribute Values: None

    :Creator: Harrison, D. and Rubinfeld, D.L.

This is a copy of UCI ML housing dataset.
http://archive.ics.uci.edu/ml/datasets/Housing


This dataset was taken from the StatLib library which is maintained at Carnegie Mellon University.

The Boston house-price data of Harrison, D. and Rubinfeld, D.L. 'Hedonic
prices and the demand for clean air', J. Environ. Economics & Management,
vol.5, 81-102, 1978.   Used in Belsley, Kuh & Welsch, 'Regression diagnostics
...', Wiley, 1980.   N.B. Various transformations are used in the table on
pages 244-261 of the latter.

The Boston house-price data has been used in many machine learning papers that address regression
problems.

**References**

   - Belsley, Kuh & Welsch, 'Regression diagnostics: Identifying Influential Data and Sources of Collinearity', Wiley, 1980. 244-261.
   - Quinlan,R. (1993). Combining Instance-Based and Model-Based Learning. In Proceedings on the Tenth International Conference of Machine Learning, 236-243, University of Massachusetts, Amherst. Morgan Kaufmann.
   - many more! (see http://archive.ics.uci.edu/ml/datasets/Housing)

In [2]:
# Split the data into train and test set
X = boston.data
y = boston.target
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.3)

In [24]:
#GRADED
# (a) Use statsmodels to build a linear regression model with X_Train, y_train as training data
# (b) Generate predictions on X_test and call it yhat
# model = smf.OLS(...)
# result = model.fit()
# yhat = result.predict(...)
# Measure the mean square error (https://en.wikipedia.org/wiki/Mean_squared_error)
# mse_error = np.mean((yhat-y_test) ** 2)
# (c) Print the mean squared error
# (d) Now, build the same model using sklearn.ensemble.RandomForestRegressor() while using X_train, y_train as training data
# (e) Generate mean square error on the test set
# (f) Compare the mean square error and determine which regressor is better
# model = sklearn.ensemble...
# model.fit(...)
# yhat = model.predict(...)
# mse_error2=np.mean((yhat-y_test)**2)

In [37]:
results = smf.ols('y_train ~ X_train',data = boston).fit()
print(results.params)

Intercept      39.223783
X_train[0]     -0.094903
X_train[1]      0.035111
X_train[2]      0.034422
X_train[3]      3.303209
X_train[4]    -15.896350
X_train[5]      3.269496
X_train[6]      0.004683
X_train[7]     -1.221143
X_train[8]      0.334833
X_train[9]     -0.013160
X_train[10]    -0.993282
X_train[11]     0.009095
X_train[12]    -0.592630
dtype: float64

In [38]:
model = smf.ols('y_test ~ X_test',data = boston)
result = model.fit()
result.summary()
yhat=result.predict(X_test)
print(yhat)

0      19.987664
1      21.091584
2      33.432639
3      38.846251
4      18.445728
5      17.793699
6       6.583505
7      31.866462
8      31.388593
9      18.299535
10     19.378959
11     32.510819
12     13.165525
13     24.324299
14     35.995310
15     32.801902
16     45.163329
17     26.697619
18     26.369306
19     24.695196
20     36.026256
21     36.705123
22     30.721533
23     11.981294
24     11.249671
25     32.841082
26     17.709319
27     23.515993
28     24.033152
29     21.985362
         ...
122    26.037488
123    13.744948
124    18.869106
125    21.012481
126    45.584539
127    27.614229
128    19.900000
129    16.186396
130    18.966222
131    23.674161
132    25.652546
133    20.830852
134    17.784555
135    24.979712
136    24.500247
137    37.162176
138    13.804626
139    27.830682
140    19.933375
141    22.096410
142    17.681565
143    33.472877
144    18.830830
145    25.847998
146    18.264295
147     6.048697
148    20.900678
149    20.906107
150    15.201549
151     7.492138
Length: 152, dtype: float64

In [39]:
mse_error = np.mean((yhat-y_test) ** 2)
print(mse_error)

18.8888205408931

In [36]:
# (d) Now, build the same model using sklearn.ensemble.RandomForestRegressor() while using X_train, y_train as training data
model = sklearn.ensemble.RandomForestRegressor()
model.fit(X_train,y_train)
yhat = model.predict(X_test)
mse_error2 = np.mean((yhat-y_test)**2)
print(mse_error2)

12.569279605263157

In [ ]:
# Random Tree Regression is better as marginal error is smaller

### Graded : Iris classification
In this example, we will use the familiar Iris dataset and build a classifier to predict if a leaf is of species 'setosa' based on sepal and petal measurements

In [35]:
iris = sklearn.datasets.load_iris()
print(iris.DESCR)

Iris Plants Database
====================

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
    :Class Distribution: 33.3% for each of 3 classes.
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML iris datasets.
http://archive.ics.uci.edu/ml/datasets/Iris

The famous Iris database, first used by Sir R.A Fisher

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

References
----------
   - Fisher,R.A. "The use of multiple measurements in taxonomic problems"
     Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
     Mathematical Statistics" (John Wiley, NY, 1950).
   - Duda,R.O., & Hart,P.E. (1973) Pattern Classification and Scene Analysis.
     (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
   - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
     Structure and Classification Rule for Recognition in Partially Exposed
     Environments".  IEEE Transactions on Pattern Analysis and Machine
     Intelligence, Vol. PAMI-2, No. 1, 67-71.
   - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
     on Information Theory, May 1972, 431-433.
   - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
     conceptual clustering system finds 3 classes in the data.
   - Many, many more ...

In [36]:
# Get the features and target variables
X=iris.data
y=(iris.target==0).astype(np.float32) # We convert a 3 class problem to is_setosa/is_not_setosa
print(np.mean(y))
# We will split the dataset into 70% training and 30% test dataset
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(X, y, test_size=0.3)

0.33333334

In [10]:
#GRADED
# (a) Use sklearn to build a classification model with X_Train, y_train as training data
# (b) Generate predictions on X_test and call it yhat
# model = sklearn.ensemble.RandomForestClassifier(n_estimators=1)
# result = model.fit(...)
# yhat_test = result.predict(X_test)
# yhat_train = ...
# (c) Measure the average precision and recall on the trianing set and the test set
# sklearn.metrics.classification_report

In [39]:
#build randomforest callsification model
model = sklearn.ensemble.RandomForestClassifier(n_estimators=1)
result = model.fit(X,y)
#generate prediction
yhat_test = result.predict(X_test)
yhat_train = result.predict(X_train)

In [38]:
# measure and recall
print(sklearn.metrics.classification_report(y_test,yhat_test))
print(sklearn.metrics.classification_report(y_train,yhat_train))

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        32
        1.0       1.00      1.00      1.00        13

avg / total       1.00      1.00      1.00        45

             precision    recall  f1-score   support

        0.0       1.00      1.00      1.00        68
        1.0       1.00      1.00      1.00        37

avg / total       1.00      1.00      1.00       105

### GRADED: Capstone project
We will start working on our capstone project this week. For this week, the task consists of
* Finding a dataset of interest. 
  - You can use the links in the supplementary materials to help you find the dataset
  - This dataset should be publicly accessible and available for download
  - Should be of interest to the class
  - The goal is to be askign and answering important questions about the data
* Describe the dataset in a manner similar to iris.DESCR, or boston.DESCR
  - The description should contain the columns in the dataset
  - Size of the dataset
  - data types of the columns
* Provide descriptive statistics of the dataset
* Provide a list of

In [60]:
df = pd.read_csv('C:/Users/luoso/Desktop/employee.csv')

In [63]:
df.describe

<bound method NDFrame.describe of                            NAME                DEPARTMENT NAME  \
0              Miller,Francis T       Boston Police Department
1       Sullivan,Patrice Murphy       Boston Police Department
2              O'Hara,Michael C       Boston Police Department
3              Whalen,Richard L       Boston Police Department
4               Kelly,Ann Marie       Boston Police Department
5             Carroll,William F       Boston Police Department
6               Connolly,John J       Boston Police Department
7                  Ivens,Paul M       Boston Police Department
8                  Kelly,John R       Boston Police Department
9               Klokman,John A.       Boston Police Department
10                Newton,Robert       Boston Police Department
11          Peters,Kenneth A Jr       Boston Police Department
12           Rodriguez,Carmen N       Boston Police Department
13             Hartgrove,Todd M       Boston Police Department
14            Younger,Vatchel S       Boston Police Department
15      Hartgrove,Christopher A       Boston Police Department
16                 Lee,George Y       Boston Police Department
17               Turner,Keith A       Boston Police Department
18              Carnell,James W       Boston Police Department
19            Crossen,Patrick J       Boston Police Department
20              Meade,Stephen M       Boston Police Department
21           Chinetti,William J       Boston Police Department
22               McGill,Kevin J       Boston Police Department
23              Canney,Joseph H       Boston Police Department
24              Fish,Michael A.       Boston Police Department
25              Terenzi,Phillip       Boston Police Department
26           Spellman,Deborah M       Boston Police Department
27                 Flynn,Anna E       Boston Police Department
28          Buchanan,Basil Mark       Boston Police Department
29          Caulfield,Richard P       Boston Police Department
...                         ...                            ...
22215            Barros,Eurides         Fam & Student Engagemt
22216         Ahmed,Said Hassan    BPS South Boston HS - Excel
22217             Assiraj,Farah              Newcomers Academy
22218             OGarro,De'Lea    BPS South Boston HS - Excel
22219         Inciarte,Himilcon                      Tobin K-8
22220     Rivera,Maria Victoria                  Green Academy
22221                Gary,Grant        BPS Chittick Elementary
22222   Harewood,Alexis Octavia     Kennedy, EM Health Academy
22223            Owens,Joy Wong           Henderson Elementary
22224       Gomez,Curtis Joseph          BPS Special Education
22225       Lake,Kimberly Marie          UP Academy Dorchester
22226           Mansfield,Laura                 BPS Burke High
22227  Rowlinson,Veronica Ramos           BPS East Boston High
22228              Demaidi,Sara            Young Achievers K-8
22229            Gonzalez,Julia      BPS Office Of Budget Mgmt
22230               Rok,Kaitlin          BPS Holmes Elementary
22231       Gilson,Brittany Ann           BPS Tynan Elementary
22232            Vanegas,Monica                      Tobin K-8
22233      Poindexter,Nicolette   BPS Substitute Teachers/Nurs
22234          Rodrigues,Anjali        BPS Boston Arts Academy
22235          Sterrer,Marina R       BPS Higginson Elementary
22236            West,Kelcy Lyn                       Lyon K-8
22237                Berman,Ann        BPS Chittick Elementary
22238            Simoes,Julie A  BPS Orchard Gardens K-8 Pilot
22239  Walkenstein,Emily Rebeca             Mildred Avenue K-8
22240         Flaherty,Thomas C       Boston Police Department
22241              Simon,Victor               Parks Department
22242              Lara,Diana D                     Edison K-8
22243     Gross,William Brenden       Boston Police Department
22244        Saint Hubert,Simon             BPS Transportation

                                TITLE       REGULAR       RETRO        OTHER  \
0             Police Lieutenant (Det)  $129,530.83          NaN  $13,694.50
1                      Office Manager   $56,921.80          NaN   $3,594.65
2                   Police Lieutenant  $124,056.64          NaN   $6,432.23
3                    Police Detective   $94,956.25   $4,985.32   $13,591.93
4              Tape Librarian I (BPD)   $69,995.34          NaN     $300.00
5       Police Offc/Hosp Liaison 4$10   $12,756.79   $2,390.14   $41,612.10
6                      Police Officer   $93,180.42   $2,027.71   $13,338.20
7                  Police Captain/DDC           NaN         NaN  $60,777.01
8               Police Sergeant (Det)   $13,827.39          NaN  $62,393.08
9       PoliceSergeant/SupvCourtCases  $107,599.31          NaN  $14,482.47
10                     Police Officer   $93,180.42   $2,646.49    $6,655.62
11                     Police Officer   $48,017.69   $3,031.83   $47,271.41
12                   Police Detective  $103,987.91   $3,455.19    $9,260.77
13                   Police Detective           NaN    $165.49   $14,175.06
14                     Police Officer           NaN    $336.74   $19,094.21
15                   Police Detective     ($380.71)    $174.05   $16,078.64
16           ChCommEquipOper I (SCTT)   $58,005.80          NaN          NaN
17                   Police Detective   $97,413.67   $3,151.35   $12,298.38
18                     Police Officer   $93,180.42   $2,259.45   $12,511.24
19                 Police Captain/DDC  $146,894.28          NaN  $22,119.73
20            Police Lieutenant (Det)  $129,530.83          NaN  $14,916.72
21              Police Sergeant (Det)  $117,408.98          NaN   $6,579.19
22                   Police Detective   $94,956.25   $4,000.20    $3,505.59
23                  Police Lieutenant  $125,070.42          NaN  $14,532.29
24      PoliceSergeant/SupvCourtCases   $14,119.37          NaN  $16,379.97
25            Police Captain-DDC/HRCD  $149,242.34          NaN   $2,420.73
26             Jr  Building Custodian   $44,002.60     $603.80      $500.00
27           ChCommEquipOper I (SCTT)   $58,497.74          NaN          NaN
28     Police Offc Comm Serv Offc 3$8   $16,371.52   $2,627.24   $42,768.77
29        Police Officer Hdq Dispatch  $103,890.60   $1,459.90      $800.00
...                               ...           ...         ...          ...
22215                     Analyst (C)   $46,176.96          NaN     $247.62
22216     Community Field Coordinator    $5,561.19          NaN          NaN
22217                         Teacher   $63,672.72          NaN   $6,775.00
22218            Employment Agreement    $2,775.00          NaN          NaN
22219                         Teacher   $56,075.86          NaN          NaN
22220               Coord-Manager (C)   $64,206.48          NaN          NaN
22221                         Teacher   $53,491.18          NaN          NaN
22222                         Teacher   $50,283.96          NaN   $3,680.00
22223                         Teacher   $65,430.96          NaN   $2,233.68
22224                 One to One Para    $4,980.07          NaN          NaN
22225            Director (Basas 10B)   $62,218.80          NaN          NaN
22226                         Teacher   $51,861.05          NaN          NaN
22227                         Teacher   $36,438.32          NaN   $1,250.00
22228                         Teacher   $47,672.83          NaN          NaN
22229                       Attendant    $4,834.98          NaN          NaN
22230                         Teacher   $54,613.18          NaN   $5,676.30
22231                         Teacher   $49,542.10          NaN   $1,250.00
22232                         Teacher   $38,912.18          NaN   $2,593.00
22233              Substitute Teacher   $16,245.78          NaN          NaN
22234                         Teacher   $47,605.95          NaN          NaN
22235                         Teacher   $34,667.97          NaN          NaN
22236                         Teacher   $36,781.54          NaN   $1,750.00
22237                         Teacher   $35,809.31          NaN   $1,250.00
22238                         Teacher   $48,752.09          NaN          NaN
22239                         Teacher   $36,781.54          NaN     $461.40
22240                  Police Officer    $1,704.01      $99.24           NaN
22241        Laborer Seasonal (Parks)    $2,777.44      $55.55           NaN
22242   Part-Time Cafeteria Attendant    $6,610.00          NaN     $122.00
22243                  Police Officer    $1,170.50          NaN          NaN
22244          Standby Cab Monitor HE    $6,212.63          NaN          NaN

          OVERTIME       INJURED       DETAIL QUINN/EDUCATION INCENTIVE  \
0       $8,150.41            NaN          NaN               $24,286.86
1       $1,548.16            NaN          NaN                       NaN
2      $29,043.67            NaN  $22,385.00                $23,260.69
3      $85,419.22        $58.03   $16,330.00                $19,971.01
4       $7,961.08            NaN          NaN                       NaN
5         $912.04            NaN          NaN                $1,563.30
6      $19,881.93            NaN  $28,934.00                $14,733.53
7              NaN    $2,658.71           NaN                  $498.51
8         $867.60            NaN          NaN                $2,074.11
9      $12,824.85            NaN  $99,640.00                $16,140.15
10     $57,979.06            NaN  $46,920.00                $14,733.53
11     $42,778.79            NaN  $13,662.00                 $8,813.10
12     $36,551.68            NaN          NaN                       NaN
13             NaN  $106,986.09           NaN                       NaN
14             NaN   $48,993.09           NaN                       NaN
15             NaN  $106,392.37           NaN                       NaN
16      $2,408.23            NaN          NaN                       NaN
17     $16,036.56            NaN     $414.00                $20,698.91
18     $14,994.74            NaN  $80,454.00                $14,733.53
19     $62,127.97            NaN   $7,020.00                $27,542.71
20     $29,581.42            NaN          NaN               $24,286.86
21     $48,778.43            NaN   $4,876.00                $17,416.49
22     $59,602.46            NaN   $5,336.00                $19,971.01
23     $22,798.36            NaN   $9,240.00                $23,131.42
24             NaN   $87,637.50           NaN               $19,079.60
25     $31,032.19            NaN  $57,540.00                $27,983.02
26        $984.78            NaN          NaN                       NaN
27        $985.18            NaN          NaN                       NaN
28             NaN           NaN   $3,588.00                 $2,968.43
29      $8,378.94            NaN          NaN                       NaN
...            ...           ...          ...                       ...
22215          NaN           NaN          NaN                       NaN
22216          NaN   $31,658.32           NaN                       NaN
22217          NaN           NaN          NaN                       NaN
22218          NaN           NaN          NaN                       NaN
22219          NaN           NaN          NaN                       NaN
22220          NaN           NaN          NaN                       NaN
22221          NaN           NaN          NaN                       NaN
22222          NaN           NaN          NaN                       NaN
22223          NaN           NaN          NaN                       NaN
22224          NaN           NaN          NaN                       NaN
22225          NaN           NaN          NaN                       NaN
22226          NaN           NaN          NaN                       NaN
22227          NaN           NaN          NaN                       NaN
22228          NaN           NaN          NaN                       NaN
22229          NaN           NaN          NaN                       NaN
22230          NaN           NaN          NaN                       NaN
22231          NaN           NaN          NaN                       NaN
22232          NaN           NaN          NaN                       NaN
22233          NaN           NaN          NaN                       NaN
22234          NaN           NaN          NaN                       NaN
22235          NaN           NaN          NaN                       NaN
22236          NaN           NaN          NaN                       NaN
22237          NaN           NaN          NaN                       NaN
22238          NaN           NaN          NaN                       NaN
22239          NaN           NaN          NaN                       NaN
22240          NaN    $5,280.78           NaN                       NaN
22241          NaN           NaN          NaN                       NaN
22242          NaN           NaN          NaN                       NaN
22243          NaN           NaN          NaN                       NaN
22244          NaN           NaN          NaN                       NaN

      TOTAL EARNINGS POSTAL
0       $175,662.60    2043
1        $62,064.61    2132
2       $205,178.23    2021
3       $235,311.76    2062
4        $78,256.42    2190
5        $59,234.37    2131
6       $172,095.79    2339
7        $63,934.23    2339
8        $79,162.18    2492
9       $250,686.78    2134
10      $222,115.12    2043
11      $163,574.82    2148
12      $153,255.55    2186
13      $121,326.64    1905
14       $68,424.04    2119
15      $122,264.35    2066
16       $60,414.03    2131
17      $150,012.87    2126
18      $218,133.38    2169
19      $265,704.69    2190
20      $198,315.83    2043
21      $195,059.09    2339
22      $187,371.51    2043
23      $194,772.49    2155
24      $137,216.44    2045
25      $268,218.28    2339
26       $46,091.18    2132
27       $59,482.92    2066
28       $68,323.96    2186
29      $114,529.44    2135
...              ...    ...
22215    $46,424.58    2186
22216    $37,219.51    2119
22217    $70,447.72    2186
22218     $2,775.00    2125
22219    $56,075.86    1721
22220    $64,206.48    1902
22221    $53,491.18    1810
22222    $53,963.96    2131
22223    $67,664.64   63139
22224     $4,980.07    2122
22225    $62,218.80    2129
22226    $51,861.05   19136
22227    $37,688.32    2180
22228    $47,672.83    2148
22229     $4,834.98    2128
22230    $60,289.48    2446
22231    $50,792.10    2067
22232    $41,505.18    2215
22233    $16,245.78    2115
22234    $47,605.95    2135
22235    $34,667.97    1835
22236    $38,531.54    1540
22237    $37,059.31    2446
22238    $48,752.09    1880
22239    $37,242.94    2138
22240     $7,084.03    2122
22241     $2,832.99    2132
22242     $6,732.00    2119
22243     $1,170.50    2125
22244     $6,212.63    2136

[22245 rows x 12 columns]>

In [ ]:
# The data set consists of 12 columns:
#Name,Department,Title,Regular,Retro,Other,Overtime,
#Injured,Detail,Quinn/Education,Total and Postal
#The first three columns are none-numeric
#The rest columns are numeric